### ISSUE TITLE
Unlimited Stock|Money

### ISSUE THREAD

**Issue by IBGnova** [Zerthick/PlayerShopsRPG#1]
When you use the command /shop set unlimited stock. It does show up that it has unlimited in the shop chat, but when you try to buy one of the items it just tells you the shop doesnt have any of those items to sell.

**Comment by Zerthick** [comment]
Interesting, I'll look into it.  Thanks!

**Comment by IBGnova** [comment]
Thanks, Please update me on any progress as we are currently using the plugin, but it only works for players at the current state as we cannot use it for an admin shop.

**Comment by Zerthick** [comment]
@IBGnova I believe I have fixed the issue in [v0.1.2](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v0.1.2)!

**Comment by IBGnova** [comment]
Amazing I will test it out and give you feedback tonight. Thank you for your help.

**Comment by Zerthick** [comment]
@IBGnova Great! Let me know if there are any other issues!

**Comment by Zerthick** [comment]
@IBGnova I'll assume this is fixed for now. Feel free to reopen the issue if it comes back!
