### ISSUE TITLE
Plugin not loading in anymore

### ISSUE THREAD

**Issue by Whazaaaaa** [Zerthick/PlayerShopsRPG#10]
Hello it seems that the plugin is not loading anymore on the server. I have put everything I could find in error in my fml log in a pastebin.
https://pastebin.ubuntu.com/23766327/

SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-428c0b2
    SpongeForge: 1.10.2-2202-5.1.0-BETA-2022
    Minecraft Forge: 12.18.3.2185

Any clue what I can do about this?

I havent really changed anything (Besides maybe the sponge version) and it just happend out of nowhere. I just heard from my players that it doesnt work anymore. The whole plugin isnt even loaded. I can't do any commands.

**Comment by Zerthick** [comment]
Did this occur after you updated to the latest version of PlayerShopsRPG perhaps?

**Comment by Zerthick** [comment]
So it looks like someone added an item with custom data to a shop and it didn't serialize properly, could you see if the issue persists on the latest release of PlayerShopsRPG, could you also paste the contents of your `shops.conf`?

**Comment by Whazaaaaa** [comment]
Latest version seems to have fixed it.

Was unaware of the new version I tend to look at this:
https://forums.spongepowered.org/t/playershopsrpg-v1-0-1-region-based-player-shops/12396
which still said 1.0.1

If for research purposes you still want the shops.conf I've added them to the post
[shops.zip](https://github.com/Zerthick/PlayerShopsRPG/files/693448/shops.zip)

Thanks!

**Comment by Zerthick** [comment]
Ah yes, that topic is outdated which is why it's been locked, PlayershopsRpg now has an [ore page](https://ore.spongepowered.org/Zerthick/PlayerShopsRPG) which I will be maintaining and keeping up to date! Glad everything works now! 😄
