### ISSUE TITLE
wrong permissions

### ISSUE THREAD

**Issue by oogienl** [Zerthick/PlayerShopsRPG#12]
just wanted to let you know that the permissions on https://github.com/Zerthick/PlayerShopsRPG/wiki/Permissions are not shown properly instead of ''commands'' its command'' example : playershopsrpg.commands.select
 should be playershopsrpg.command.select. had some problems getting these to work until i tried it this way (using LuckyPerms)

**Comment by Zerthick** [comment]
They were changed on the latest release which is why it is such on the wiki, if you are on a version of PlayerShopsRPG before version v1.1 it will be "command" instead of "commands"

https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v1.1.0
