### ISSUE TITLE
Meta Data

### ISSUE THREAD

**Issue by TooVeryIcey** [Zerthick/PlayerShopsRPG#14]
I am trying to make a spawn egg shop, but it only lets me put one kind of spawn egg...is there any WorkAround for this?

**Comment by Zerthick** [comment]
That's bizarre, it shouldn't do that. What version of PlayerShopsRPG and Sponge are you using? As a temporary fix you could rename each different type of egg you want to sell in an anvil, that would allow you to sell multiple kinds.

**Comment by TooVeryIcey** [comment]
I am using PlayerShopRPG 1.1.0 and API 6

**Comment by Zerthick** [comment]
Hmmm, API 6 may have broken some things, I'll investigate releasing an API 6 compatible build.

**Comment by TooVeryIcey** [comment]
Not sure if this is related, but I set the stock of my shops to unlimited...but it is saying that the shop is out of stock

**Comment by Zerthick** [comment]
I've identified the issue, it will be fixed in the next release which should be out soon!

**Comment by Zerthick** [comment]
Fixed in [v2.0.0](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.0)!
