### ISSUE TITLE
rent shop and destroy item

### ISSUE THREAD

**Issue by aWitch-Doctor** [Zerthick/PlayerShopsRPG#16]
I'm attempting to create shops for players to rent, when a player rented a shop from me using /shop rent # it would rent it to the player for the specified number of hours and then take money from me and give it to him instead of taking money from him. The player also couldn't destroy the item from the shop, it said in valid argument /shop item destroy. 

Are you able to make it so the shops can be owned by the server as well? On the server im running we have the server with shops and allow the player to rent them in a designated area. This lets us keep them together and clear out old ones that are no longer used. 

Is it possible to paginate the items the shops sell if they take up more then one screen of text?

Can you add a config setting to allow us to change the time a player rents for from hour to day/week/month.

**Comment by Zerthick** [comment]
Ooops! That rent money transfer is definitely a bug, I'll be sure to fix that in the next release.

Sever owned-shops is also I feature I intend to add in the next release

The list of items should also paginate it's too long, could you upload a screenshot of the behavior you're seeing?

I'll definitely look into allowing the user to specify rent intervals in units other than hours.

Cheers

**Comment by aWitch-Doctor** [comment]
mkay so if the player adds a lot of items to their shop it will show them on 1 page when a player types /shop browse
I hope this helps, if you need anythingelse let me know. Thank you.
https://puu.sh/vg9UA/7976f10317.png
https://puu.sh/vg9Vw/ba52feff93.png

**Comment by Zerthick** [comment]
Should be fixed in (v2.0.0)[https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.0]!
