### ISSUE TITLE
Unlimited stock bug

### ISSUE THREAD

**Issue by Yorkforce** [Zerthick/PlayerShopsRPG#18]
When any listed items hit the itemAmount=0 count it will show out of stock even if the unlimitedStock=true is set, however if the itemAmount=-1 or below, it will act as a true unlimited stock.

**Comment by Zerthick** [comment]
Yep, I can confirm this does indeed happen, it's going to be fixed in the next release which should be out soon!

**Comment by Zerthick** [comment]
Fixed in [v2.0.0](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.0)!
