### ISSUE TITLE
Space between items in shops.

### ISSUE THREAD

**Issue by IBGnova** [Zerthick/PlayerShopsRPG#2]
Hey, 

Sorry I didnt get back to you about the unlimited money/stock thing I totally forgot about it, that bug was fixed and I really thank you for it, but now I have more of a request then a bug. I would like to see if it would be possible to add spaces between items when you do /shop browse, because as it is now item text seems to be inside each other sometimes. 

Thanks,
Nova

**Comment by Zerthick** [comment]
Sure I can do that!

**Comment by Zerthick** [comment]
Added in [v0.1.3](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v0.1.3)!
