### ISSUE TITLE
Shops dissapear after server restart. 

### ISSUE THREAD

**Issue by TherealJez** [Zerthick/PlayerShopsRPG#22]
Basically what the title says, nothing is left of any shop if I restart my server.

**Comment by Zerthick** [comment]
What version of Sponge are you running?

**Comment by TherealJez** [comment]
spongeforge-1.11.2-2282-7.0.0-BETA-2327.jar and PlayerShopsRPGv1.1.0

**Comment by Zerthick** [comment]
Ah, well I haven't released build for API 6 & 7 yet so I'll be sure to resolve this before I do.

**Comment by TherealJez** [comment]
Thanks!

**Comment by Zerthick** [comment]
Does this still occur on [v2.0.2](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.2)?

**Comment by aWitch-Doctor** [comment]
Im using Sponge Vanilla api 5 and this happened to me. All the recent changes to shops were undone. It's like it reverted to a previous date.

**Comment by Zerthick** [comment]
Did there happen to be any error messages when the server shutdown?

**Comment by aWitch-Doctor** [comment]
none that i could find, I checked both when it shutdown and when it restarted and everything looked normal. Later tonight when the server empties out i can try restarting it again to recreate the issue. I might have more info for you then.

**Comment by aWitch-Doctor** [comment]
I can recreate the issue, but there are no errors anywhere in the logs. I don't know anything about databases so I can't even guess at what is happening...

**Comment by Zerthick** [comment]
I think I've identified the issue, I'll try to have a fix out soon.

**Comment by Zerthick** [comment]
See if the issue persists in [v2.0.4](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.4)

**Comment by Zerthick** [comment]
I believe this issue has been resolved.
