### ISSUE TITLE
Have you a plan to update the plugin for mc 1.11 and 1.12?

### ISSUE THREAD

**Issue by 5igm** [Zerthick/PlayerShopsRPG#24]
Hi! I like your plugin very much. But my server is in mc 1.11. Have you a plan to update the plugin to API6 or API7? Thank you very much.

**Comment by Zerthick** [comment]
Yes, an API 6 build is in the works, it's been so delayed because I've been optimizing the core of the plugin and fixing a lot of bugs 😄

**Comment by 5igm** [comment]
Thanks for your work. I'm so expected to the new plugin.

**Comment by Zerthick** [comment]
1.11 support added in [v2.0.2](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.2)!
