### ISSUE TITLE
2x Dupe bug

### ISSUE THREAD

**Issue by Whazaaaaa** [Zerthick/PlayerShopsRPG#26]
**Dupe bug 1:** 
1. Make shop
2. Add whatever item
3. do /shop item remove # -10 and it will add 10 items with no cost

So adding the minus f's up the system. I thought it already checked for a minus I thought I read in some changelog. But I guess not.
I tested this myself and it works :/
http://recordit.co/2FQlAK4GXW
That is a recording of me doing it just now if that helps.

Tested on: spongeforge-1.10.2-2281-5.2.0-BETA-2407
Modpack: https://minecraft.curseforge.com/projects/foolcraft/files/2415352

**Dupe bug 2:**
1. create a shop
2. add an Item to sell to the Shop
3. restock the shop with /shop item add while holding the item in your hand

it doesnt take the item out of your inve when you add it to the shop, so just buy it back from your Own shop for a price of 0 and bam, you have double the items

But seeing as this is a API 6 issue and 1.11.2, I guess there not much to be done besides a whole new version.

Tested on: spongeforge-1.11.2-2315-6.1.0-BETA-2398
Modpack: https://minecraft.curseforge.com/projects/all-the-mods-2/files/2439222

**Comment by Zerthick** [comment]
**Dupe Bug 1:**
Confirmed, looks like I forgot a check on the add and remove commands, good thing is it's not easy to fix :smile: 

**Dupe Bug 2:**
This is expected as the way inventories are handled was changed in Sponge API 6.x, it will have to wait until an update to that version of Sponge for a fix.

**Comment by Zerthick** [comment]
The first dupe bug has been fixed in [v2.0.1](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.1)!

**Comment by Whazaaaaa** [comment]
I do not expect the second dupe bug issue to persist when theres a proper API 6 port of the plugin.
