### ISSUE TITLE
Wrong location

### ISSUE THREAD

**Issue by Whazaaaaa** [Zerthick/PlayerShopsRPG#28]
EDIT: It seems that I forgot to finish my title sorry.
Should have been "Wrong location shops database"

It seems that the plugins doesnt put the database in the correct location.
I for example have a custom folder set in the sponge configs where the configs for every plugin is put into. So I dont have all the configs from the mods mixed with the plugins. Now the normal configs are correctly put into that folder but it seems the database is set to the normal root/config/playershopsrpg folder. Any reason as to why this is so? And can this be set to the normal configs folder provides by sponge?

While updating a modpack I remove all configs to replace them for the new configs (for the new version) in the new release. Not knowing playershopsrpg was in there I deleted all my players shops :(. Which is why im asking for this feature/fix ^^

**Comment by Zerthick** [comment]
Ooops, sorry about that 😦 I'll release a patch to make it fetch the directory from Sponge instead.
