### ISSUE TITLE
Suggestion: Could you add a message file?

### ISSUE THREAD

**Issue by 5igm** [Zerthick/PlayerShopsRPG#3]
I think this is an amazing plugin. I want to translate it. Could you add a message file for it?

**Comment by Zerthick** [comment]
That would be amazing! I'll definitely add in a message file in the next major release :smiley:

**Comment by Zerthick** [comment]
@5igm Sorry it took forever But I've now added a message file which you have find [here](https://github.com/Zerthick/PlayerShopsRPG/blob/master/src/main/resources/assets/playershopsrpg/messages_en_US.conf)! Feel free to create a pull request to add translations in different languages, thanks so much!

**Comment by 5igm** [comment]
Thanks so much.
