### ISSUE TITLE
shop item add fails in 2.0.4

### ISSUE THREAD

**Issue by rdalkire** [Zerthick/PlayerShopsRPG#34]
In version 2.0.4, when I use `/shop item add`, the items in-hand do not disappear or reduce, though the shop inventory for the item **does** increase.

I don't see any error messages in client or server consoles.

Other basic functionality like item create, and item removal (via manage) works OK.

When I revert to 2.0.3, the `add` command works normally again.

**Comment by Zerthick** [comment]
What version of Minecraft are you using? `v2.0.4` is only compatible with Minecraft 1.10.2 *not* 1.11.2. I'll be releasing a 1.11.2 compatible build soon 😄

**Comment by rdalkire** [comment]
Whoops right. I'm at 1.11.2.  I see now, you do say 1.10 in the release comments.  I look forward to your 1.11.2 version then.  This is for the server found from technic pack "Ape42 World 8".
