### ISSUE TITLE
API7

### ISSUE THREAD

**Issue by Whazaaaaa** [Zerthick/PlayerShopsRPG#35]
Hello is it possible to port the PlayerShopsRPG for API7? That would be amazing thank you.

**Comment by Zerthick** [comment]
Yep! As soon as there are stable API 7 builds I plan to update 😄

**Comment by Whazaaaaa** [comment]
Perhaps a beta build? :D
I could really use this plugin on 1.12.2 ^^

**Comment by Wissi** [comment]
Us also. We are migrating to a 1.12 already.
Even a beta build would be really much appreciated. ^^

**Comment by Zerthick** [comment]
I'll see what I can do 😉

**Comment by Zerthick** [comment]
Here's a very quick and dirty dev build for testing: https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v0.2.0 Everything appears to be working correctly but please **backup your data** before attempting to use it and be sure to let me know if there are any issues.
