### ISSUE TITLE
/shop select cancel

### ISSUE THREAD

**Issue by Whazaaaaa** [Zerthick/PlayerShopsRPG#37]
I've had some people stuck in /shop select. Is there any way to stop using /shop select?
If not can there be a /shop cancel or /shop select cancel command?

Thank you.

**Comment by Zerthick** [comment]
Yep! `/shop select clear` is what you want. You can view all commands/options in the [wiki](https://github.com/Zerthick/PlayerShopsRPG/wiki/Commands)! 😄
