### ISSUE TITLE
i cant sell or add item. + error

### ISSUE THREAD

**Issue by Lajtmen** [Zerthick/PlayerShopsRPG#38]
i cant sell or item add item. 
i got this error : org.spongepowered.api.item.inventory.entity.PlayerInventory.queryAny([Lorg/spongepowered/api/item/inventory/ItemStack;)Lorg/spongepowered/api/item/inventory/Inventory
![vystrizek](https://user-images.githubusercontent.com/33398720/33526536-58db033c-d843-11e7-8e8f-e999a2fe21d9.PNG)

**Comment by Zerthick** [comment]
Are you running the command manually or clicking on the links in the UI? What version of PlayerShopsRPG and Sponge are you running?

**Comment by Lajtmen** [comment]
Latest version of PlayerShops and sponge version 2477 1.10.2 , i tried both methods that you mentioned.

**Comment by Zerthick** [comment]
The latest version of PlayerShopsRPG, v0.2.0, is for Sponge API 7 (1.12.2) and will **not** work on API 6 (1.10.2), please see if the issue persists on the last stable release for 1.10.2, [v2.0.5](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.5)

**Comment by Lajtmen** [comment]
ok , it worked thanks.
