### ISSUE TITLE
Players able to buy items without free inventory slots.

### ISSUE THREAD

**Issue by AlexxSeven** [Zerthick/PlayerShopsRPG#4]
As requested, i've brought this into the git hub issues section.

One of the issues i've noticed with the current version included, is that players are able to still use "/shop item buy" with full inventories. Resulting in them losing the money from the purchase, but not getting anything in return. this is especially true for admin shops.

I currently do not have a log of the events that occur during this as no errors are thrown out in my console.

**Comment by Zerthick** [comment]
Thanks for bringing this to my attention, I'll look into creating a fix in the next release.
