### ISSUE TITLE
Input command 'browse' was not a valid subcommand. 

### ISSUE THREAD

**Issue by Rosychu** [Zerthick/PlayerShopsRPG#42]
Updated to the latest PlayerShopsRPG with Sponge 7, for version 1.12.2. 
The usual /shop options only bring up: /shop b, buy s, stock - which is from I suspect, the Total Economy plugin, as they've recently added chest shops - I couldn't see a way to disable it either.

I can get around that by specifying the plugin of course like:
/playershopsrpg:shop browse & such

Which works for making/ browsing/ destroying/ adding items to the shop- but not when it comes to interaction with the shop part. As in, I _cannot_ : Buy, Sell, Manage, or do Owner stuff with it.

I'm not sure if this is a bug, or something I'm doing wrong, but is there a way around this?
Thank you in advance.

![](https://i.imgur.com/DZ0Pggi.png)

**Comment by Rosychu** [comment]
We ended up switching economy plugins, and everything is working fine again.

**Comment by Zerthick** [comment]
Yes, this is due to total economy also having a shop command. You can fix this by using the aliases section of the Sponge global.conf https://docs.spongepowered.org/stable/en/server/getting-started/configuration/sponge-conf.html to set the PlayerShopsRPG command to take precedent

**Comment by Rosychu** [comment]
Ah, cheers, I didn't know that was a thing! Sorry about it all, thank you very much though, this is helpful.
