### ISSUE TITLE
Shop's does not save

### ISSUE THREAD

**Issue by yololetsplay** [Zerthick/PlayerShopsRPG#6]
I got an exception if I stop the server and everything saves.
Please look at attached files.
[playershopsrpg_bug.txt](https://github.com/Zerthick/PlayerShopsRPG/files/530624/playershopsrpg_bug.txt)

Greetz,
yololetsplay

**Comment by yololetsplay** [comment]
I found out that it saves my shops in config, but only position and the money. If the server restarts items are deleted.

**Comment by yololetsplay** [comment]
It saves only shops without items, shops with items are not in config. Using spongeforge BETA 1687.

**Comment by yololetsplay** [comment]
Finally, I tried it using a fresh server - same problem. Shops with items in it will not get created in config, only shops with money and without items.

**Comment by Zerthick** [comment]
This seems to be a bug within the Sponge API itself, does this still occur on the latest release?  I'll look into this.

**Comment by yololetsplay** [comment]
Oh old one.
Finally I found out if u wanna buy or sell an amount of "64" the shop does not work also in newest version.
Besides if u trade magic books the shop does no longer work after server restart.

And to answer ur question: Sell also works currently :]

**Comment by Zerthick** [comment]
Based on your comment I believe this issue has been resolved, feel free to reopen it if that is not the case.
