### ISSUE TITLE
Commands broken

### ISSUE THREAD

**Issue by Bennyboy1695** [Zerthick/PlayerShopsRPG#7]
As reading the page on how to setup a shop we tried to setup one up and it failed, no output was being gotten from the commands. But if i do /playershopsrpg:shop i would actually get output back from the commands

**Comment by Zerthick** [comment]
What version of Sponge and PlayerShopsRPG are you running?

**Comment by Bennyboy1695** [comment]
![image](https://cloud.githubusercontent.com/assets/11559693/21144477/babfcc0e-c142-11e6-81ae-33b559e026f0.png)
Latest version of PlayerShopsRpg

**Comment by Zerthick** [comment]
I'm unable to replicate that bug, my guess is that you have another plugin installed that also has a `/shop` command that is shadowing mine, meaning you have to use the extended `/playershopsrpg:shop` form.

**Comment by Zerthick** [comment]
I'm going to close this issue, as I was unable to replicate this bug, if the problem persists, feel free to reopen it.
