### ISSUE TITLE
Shop error when sell item

### ISSUE THREAD

**Issue by realKSMC** [Zerthick/PlayerShopsRPG#8]
Using spongeforge-1.11-2178-6.0.0-BETA-1999 and if I created an shop and wanna sell e.g. dirt for 0.1 coins per piece, it tells me for example "You do not have 5 dirt(s)." if i try sell 5 dirts and I have these in my inventory.

**Comment by yololetsplay** [comment]
Btw it says me nothing in concole.

**Comment by yololetsplay** [comment]
Also /item add does not work, just btw.

**Comment by Zerthick** [comment]
This is most likely due to changes in Sponge API 6 (Minecraft 1.11), currently I'm only supporting API 5 (Minecraft 1.10), so there may be issues like this if you are using a Sponge API version higher. Once I release an API 6 version of PlayerShopsRPG I'll be sure to test this functionality to ensure it isn't broken 😄

**Comment by yololetsplay** [comment]
It would be great if you release an API 6 beta version soon ;] I would donate for that, bc I really need this for my RPG server ;)

**Comment by Zerthick** [comment]
So I've attempted to do an experimental build of PlayerShopsRPG on API 6, however I've discovered that these issues are related to a bug in the Sponge API itself, meaning it's out of my control to fix 😦 I did however create an issue for the bug https://github.com/SpongePowered/SpongeCommon/issues/1121 which you can follow to see when it gets resolved!

**Comment by Zerthick** [comment]
Bit more info, they are aware of the issue and a fix has been created, we just have to wait for it to be merged in 😄

**Comment by Zerthick** [comment]
Sorry it took so long, API 6 support added in [v2.0.2](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.2)! 😃
