### ISSUE TITLE
Selling negative item quantity

### ISSUE THREAD

**Issue by sephkurai** [Zerthick/PlayerShopsRPG#9]
If someone clicks to sell/buy an item to the shop and types a negative number instead of a positive number it will take the items from the stores stock instead of from the player.

**Comment by Zerthick** [comment]
Ooops, looks like I forgot to do a bounds check! I'll be sure to release a patch soon to fix this. 😃

**Comment by Zerthick** [comment]
Should be fixed in [Release 1.1.0](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v1.1.0)! 😄
